Repository unl/wdntemplates, pull requests merged in 2020-02, with the labels that each got.

#1379 Implement DCF Webp and JS checks.
  package-lock.json
  wdn/templates_5.1/includes/global/head-2-local.html
  wdn/templates_5.1/includes/global/head-2.html
  wdn/templates_5.1/js-src/mustard-initializer.babel.js
  wdn/templates_5.1/js-src/utility-scripts/testForWebP.js
  wdn/templates_5.1/scss/components/_components.search.scss
Labels: 5.1

#1381 update polyfill.io get params
  wdn/templates_5.1/js-src/mustard-initializer.babel.js
Labels: 5.1

#1380 Update IDM to retrieve logged in user data
  debug.shtml
  wdn/templates_5.0/js-src/idm.babel.js
Labels: 5.0

#1386 Configure and style DCF tabs
  Gruntfile.js
  debug.shtml
  package-lock.json
  package.json
  wdn/templates_5.1/js-src/js-css/tabs.scss
  wdn/templates_5.1/js-src/modals.babel.js
  wdn/templates_5.1/js-src/tabs.babel.js
  wdn/templates_5.1/js-src/tabs.js
  wdn/templates_5.1/scss/components/_components.modals.scss
  wdn/templates_5.1/scss/critical.tmp.scss
  wdn/templates_5.1/scss/deprecated.tmp.scss
  wdn/templates_5.1/scss/main.tmp.scss
  wdn/templates_5.1/scss/pre.tmp.scss
  wdn/templates_5.1/scss/print.tmp.scss
  wdn/templates_5.1/scss/variables/_variables.tabs.scss
Labels: 5.1, CSS, JavaScript

#1387 Update color variables and mixins
  wdn/templates_5.1/js-src/js-css/monthwidget.scss
  wdn/templates_5.1/js-src/plugins/ui/css/jquery-ui-wdn.scss
  wdn/templates_5.1/scss/components/_components.buttons.scss
  wdn/templates_5.1/scss/components/_components.footer.scss
  wdn/templates_5.1/scss/components/_components.forms-checkboxes-radios.scss
  wdn/templates_5.1/scss/components/_components.forms-selects.scss
  wdn/templates_5.1/scss/components/_components.forms.scss
  wdn/templates_5.1/scss/components/_components.header.scss
  wdn/templates_5.1/scss/components/_components.search.scss
  wdn/templates_5.1/scss/critical.tmp.scss
  wdn/templates_5.1/scss/deprecated.tmp.scss
  wdn/templates_5.1/scss/deprecated/deprecated.forms.scss
  wdn/templates_5.1/scss/deprecated/deprecated.images.scss
  wdn/templates_5.1/scss/deprecated/deprecated.tables.scss
  wdn/templates_5.1/scss/deprecated/deprecated.text.scss
  wdn/templates_5.1/scss/elements/_elements.tables.scss
  wdn/templates_5.1/scss/main.tmp.scss
  wdn/templates_5.1/scss/pre.tmp.scss
  wdn/templates_5.1/scss/print.tmp.scss
  wdn/templates_5.1/scss/variables/_variables.body.scss
  wdn/templates_5.1/scss/variables/_variables.colors.scss
  wdn/templates_5.1/scss/variables/_variables.footer.scss
Labels: 5.1, CSS

#1389 Remove unused header variables
  wdn/templates_5.1/scss/variables/_variables.sizing.scss
Labels: 5.1, CSS

#1388 Add D3.js library
  wdn/templates_5.1/js-src/plugins/d3/API.md
  wdn/templates_5.1/js-src/plugins/d3/CHANGES.md
  wdn/templates_5.1/js-src/plugins/d3/LICENSE
  wdn/templates_5.1/js-src/plugins/d3/README.md
  wdn/templates_5.1/js-src/plugins/d3/d3.js
Labels: 5.1, JavaScript
