Repository unl/wdntemplates, pull requests merged in 2020-04, with the labels that each got.

#1403 Add styles scoped for :visited inverse buttons
  wdn/templates_5.1/scss/components/_components.buttons.scss
Labels: 5.1, CSS

#1408 Update DCF (5.1)
  package-lock.json
  package.json
Labels: 5.1

#1409 Make banner xhr request async
  wdn/templates_5.1/includes/global/header-global-1.html
Labels: 5.1, JavaScript

#1410 Make banner xhr request async
  package-lock.json
  wdn/templates_5.0/includes/global/header-global-1.html
Labels: 5.0, JavaScript

#1406 Add colors, background colors; remove WebP grit background
  wdn/templates_5.1/scss/critical.tmp.scss
  wdn/templates_5.1/scss/deprecated.tmp.scss
  wdn/templates_5.1/scss/legacy.tmp.scss
  wdn/templates_5.1/scss/main.tmp.scss
  wdn/templates_5.1/scss/mixins/_mixins.background-colors.scss
  wdn/templates_5.1/scss/mixins/_mixins.background-images.scss
  wdn/templates_5.1/scss/mixins/_mixins.colors.scss
  wdn/templates_5.1/scss/pre.tmp.scss
  wdn/templates_5.1/scss/print.tmp.scss
  wdn/templates_5.1/scss/utilities/_utilities.background-colors.scss
  wdn/templates_5.1/scss/utilities/_utilities.background-images.scss
  wdn/templates_5.1/scss/utilities/_utilities.backgrounds.scss
  wdn/templates_5.1/scss/utilities/_utilities.colors.scss
  wdn/templates_5.1/scss/variables/_variables.colors.scss
Labels: 5.1, CSS

#1407 Add Liberator web font
  wdn/templates_5.1/fonts/liberator/liberator-heavyitalic.woff
  wdn/templates_5.1/fonts/liberator/liberator-heavyitalic.woff2
  wdn/templates_5.1/includes/global/head-2-local.html
  wdn/templates_5.1/includes/global/head-2.html
Labels: 5.1, CSS, HTML

#1412 Revert warning color value
  wdn/templates_5.1/scss/variables/_variables.colors.scss
Labels: 5.1, CSS

#1405 Prepend banner to body if no skip nav
  wdn/templates_5.0/includes/global/header-global-1.html
Labels: 5.0

#1404 Prepend banner to body if no skip nav
  wdn/templates_5.1/includes/global/header-global-1.html
Labels: 5.1
