Repository unl/wdntemplates, pull requests merged in 2021-04, with the labels that each got.

#1500 Bump npm y18n
  package-lock.json
  package.json
Labels: 5.3

#1501 Update DCF
  package-lock.json
Labels: 5.3

#1499 Rename manifest.webmanifest.json to manifest.webmanifest to prevent 404
  wdn/templates_5.3/includes/global/favicon/manifest.webmanifest
Labels: 5.3, Bug

#1502 Add additional lengths (height, width, margin, padding)
  package-lock.json
  wdn/templates_5.3/scss/variables/_variables.sizing.scss
Labels: 5.3, CSS

#1503 Remove object-fit polyfill
  Gruntfile.js
  package-lock.json
  package.json
Labels: 5.3, Bug, CSS
