Repository unl/wdntemplates, pull requests merged in 2021-12, with the labels that each got.

#1562 Add `sizes="any”` to favicon.ico
  wdn/templates_5.3/includes/global/head-2-local.html
  wdn/templates_5.3/includes/global/head-2.html
Labels: HTML, 5.3

#1561 Implement DCF Pagination
  debug.shtml
  package-lock.json
  wdn/templates_5.3/js-src/pagination.babel.js
  wdn/templates_5.3/scss/main.tmp.scss
Labels: Feature Request, 5.3

#1553 Update affiliate template(s) for 5.3
  Gruntfile.js
  Templates/affiliate.dwt
  Templates/affiliate_debug.dwt
  Templates/affiliate_local.dwt
  Templates/jsp.affiliate.dwt.jsp
  Templates/jsp.affiliate_debug.dwt.jsp
  Templates/jsp.affiliate_local.dwt.jsp
  Templates/php.affiliate.dwt.php
  Templates/php.affiliate_debug.dwt.php
  Templates/php.affiliate_local.dwt.php
  affiliate.shtml
  images/placeholder-affiliate-logo.ai
  package-lock.json
  wdn/templates_5.3/includes/global/affiliate-head-2-local.html
  wdn/templates_5.3/includes/global/affiliate-head-2.html
  wdn/templates_5.3/includes/global/affiliate-nav-toggle-group-1.html
  wdn/templates_5.3/includes/global/affiliate-nav-toggle-group-2.html
  wdn/templates_5.3/includes/local/affiliate-custom.css
  wdn/templates_5.3/includes/local/affiliate-footer.html
  wdn/templates_5.3/includes/local/affiliate-header-global-1.html
  wdn/templates_5.3/includes/local/affiliate-idm.html
  wdn/templates_5.3/includes/local/affiliate-logo-lockup-1.html
  wdn/templates_5.3/includes/local/affiliate-mobile-idm.html
  wdn/templates_5.3/includes/local/affiliate-mobile-search.html
  wdn/templates_5.3/includes/local/affiliate-search.html
  wdn/templates_5.3/scss/affiliate.scss
  wdn/templates_5.3/scss/affiliate.tmp.scss
  wdn/templates_5.3/scss/generic/_generic.color-scheme.scss
  wdn/templates_5.3/scss/mixins/_mixins.background-colors.scss
  wdn/templates_5.3/tools/bookmarklets/dark-mode-toggle/dark-mode-toggle.css
Labels: 5.3
