Repository unl/wdntemplates, pull requests merged in 2021-08, with the labels that each got.

#1530 Update incident reporting link in footer from TIPS to UNL Report
  wdn/templates_5.3/includes/global/footer-global-2.html
Labels: HTML, RELEASE BLOCKER, 5.3

#1528 Hide icon when no time is set for event
  wdn/templates_5.3/js-src/events-band.js
Labels: Bug, JavaScript, HTML, 5.3

#1529 Event plugin: support layouts
  wdn/templates_5.3/js-src/events-band.js
  wdn/templates_5.3/js-src/events.babel.js
  wdn/templates_5.3/js-src/events.js
Labels: Feature Request, 5.3
