Repository unl/wdntemplates, pull requests merged in 2023-08, with the labels that each got.

#1691 Added brand-kappa and orange
  wdn/templates_5.3/scss/mixins/_mixins.background-colors.scss
  wdn/templates_5.3/scss/mixins/_mixins.colors.scss
  wdn/templates_5.3/scss/utilities/_utilities.background-colors.scss
  wdn/templates_5.3/scss/utilities/_utilities.colors.scss
  wdn/templates_5.3/scss/variables/_variables.color-palette.scss
Labels: Feature Request

#1689 Updated for new version of search
  wdn/templates_5.3/js-src/search.babel.js
Labels: dependencies

#1692 Adjust modal-wrapper max-height
  wdn/templates_5.3/scss/variables/_variables.modals.scss
Labels: CSS, 5.3

#1697 Update README for 5.3
  README.md
Labels: Communication, 5.3

#1698 Add dark-mode-only button styles
  wdn/templates_5.3/scss/components/_components.buttons.scss
Labels: Feature Request, CSS, Dark Mode, 5.3
