Repository unl/wdntemplates, pull requests merged in 2023-06, with the labels that each got.

#1675 Tabs update
  debug.shtml
  package-lock.json
  wdn/templates_5.3/js-src/tabs.babel.js
Labels: Feature Request

#1673 Update events component layout
  wdn/templates_5.3/js-src/events.babel.js
  wdn/templates_5.3/js-src/js-css/events.scss
Labels: JavaScript, CSS, HTML, 5.3

#1679 Bump DCF
  package-lock.json
Labels: dependencies

#1680 Bumped dcf version
  package-lock.json
Labels: dependencies

#1674 Analytics update
  Gruntfile.js
  README.md
  package.json
  wdn/templates_5.3/js-src/analytics.babel.js
  wdn/templates_5.3/js-src/ga.js
Labels: dependencies

#1683 re-added the wdn_tabs
  wdn/templates_5.3/js-src/tabs.babel.js
Labels: Feature Request

#1684 Add background diagonal gradients mixin/utility
  wdn/templates_5.3/scss/mixins/_mixins.background-images.scss
  wdn/templates_5.3/scss/utilities/_utilities.background-images.scss
Labels: CSS, 5.3
